### ISSUE TITLE
Django 2.0.x supported?

### ISSUE THREAD

**Issue by EDario333** [xrmx/django-fancytree#14]
Hi! I got the error: 

ImportError: cannot import name 'force_unicode'

In fancytree/widgets.py", line 8

I supposed that this widget doesn't work with Django 2.0.x, Am I right?

P. S.: I'm working with Django 2.0.2, django-mptt 0.9.0 and django-fancytree 0.4.0.

I tried to run (`./manage.py runserver`) the treewidget app but the OS freezing (os.PS file was created); I supposed that the example app was developed in a django earlier version than 2.0. Am I right? And, do you know how can I test it in django 2.0?

**Comment by xrmx** [comment]
If it fails I'd say it does not :) I'll gladly review any PR fixing things for 2.0.

**Comment by EDario333** [comment]
I've created a PR. I hope I can colaborate with u guys, it's a such great widget!

**Comment by EDario333** [comment]
By the way, I'm stuck with this:
When my page process the request (with POST method) the param with the multiple values are repeated through the same name, I mean:
`http://127.0.0.1:8000/xyz/abc/?csrfmiddlewaretoken=...&categories=1&categories=2&tags=30&tags=31`

So, why only the last element is saved on DB? How can I solve this? Any suggestion?

Here is a fragment of my model class:
```
class XYZ(models.Model):
  # Code...
  categories = models.ManyToManyField(Categories, blank=True, null=True, default=None, verbose_name=_('Categories'))

  tags = TaggableManager(through=TaggedXYZ, blank=True, verbose_name=_('Tags'))

  # More code...
```

My views.py:
```
class TagsAutoComplete(autocomplete.Select2QuerySetView):
  def get_queryset(self):
    # Don't forget to filter out results depending on the visitor !
    if not self.request.user.is_authenticated:
      return Tag.objects.none()

    qs = Tag.objects.all()

    if self.q:
      qs = qs.filter(name__istartswith=self.q)

    return qs

class CategoriesAutoComplete(autocomplete.Select2QuerySetView):
  def get_queryset(self):
    # Don't forget to filter out results depending on the visitor !
    if not self.request.user.is_authenticated:
      return Categories.objects.none()

    qs = Categories.objects.all()

    if self.q:
      qs = qs.filter(category__istartswith=self.q)

    return qs
```
My page code:
```
class CreateXYZPage(Page):
  template = 'xyz/add.html'

  def get_context(self, request, *args, **kwargs):
    context = super(Page, self).get_context(request, *args, **kwargs)
    form = XYZCreateForm()
    context['form'] = form
    context['page'] = self

    if request.method == 'POST':
      vals = {
        'var1': request.POST['var'],
        'var2': request.POST['var2'],
        'var_n': request.POST['var_n'],
      }
      cats = request.POST['categories']
      tags = request.POST['tags']
      # At this point cats and tags have a 1 length size and only contains the last element (see the URL request at the beginning)
      # But if I do:
      print(cats)
      # The output is all the elements. I.e. ['1', '2']
      # Then: why only the last element is saved on DB? How can I solve this? Any suggestion?

    return context
```

And finally the urls.py:
```
urlpatterns = [
  url(
    r'^tags/$',
    TagsAutoComplete.as_view(create_field='name'),
    name='tags-autocomplete',
  ),
  
  url(
    r'^categories/$',
    CategoriesAutoComplete.as_view(create_field='category'),
    name='categories-autocomplete',
  ),
]
```

I think that's all. Thank you 4 ur support!

Cheers!

**Comment by EDario333** [comment]
@xrmx I'm a little newbie with Git. This is the scenario:
(1) I tried to clone the repo with:
`git clone https://github.com/xrmx/django-fancytree.git`
And I got the error message: `fatal: Unable to find remote helper for 'https'`
I already have libcurl4-openssl-dev which it seems to be the error cause (https://stackoverflow.com/questions/8329485/unable-to-find-remote-helper-for-https-during-git-clone)
(2) So I clonned with:
`git clone git://github.com/xrmx/django-fancytree.git`
Long story short: I can't make a push, pull request and anything else on the repo. 
```
fatal: remote error: 
  You can't push to git://github.com/xrmx/django-fancytree.git
  Use https://github.com/xrmx/django-fancytree.git
```
Then I've created a fork (https://github.com/EDario333/django-fancytree) and there is my PR.

Such a mess, isn't? Suggestions?

P. S.: I also tried with:
```
git clone ssh://EDario333@github.com/xrmx/django-fancytree.git
git clone ssh://EDario333@github.com/django-fancytree.git
```

And in both cases I have:
```
Clonning into 'django-fancytree'...
Permission denied (publickey).
fatal: can't read the repo <--- Original is in spanish

```
And something about privileges and that the repo exists.

**Comment by xrmx** [comment]
@EDario333 I think github has plenty of documentation around https://help.github.com/articles/cloning-a-repository-from-github/
